# Generated by Django 2.1.5 on 2019-03-05 03:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Null', max_length=250)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='Null')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='restaurants.Restaurant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
