# Generated by Django 2.1.5 on 2019-01-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Đà Nẵng', max_length=250)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(default='Núi', max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('images', models.FileField(default='/default/images.jpg', upload_to='place/')),
                ('review', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
