# Generated by Django 2.1.5 on 2019-01-17 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='place',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 17, 14, 16, 52, 650957)),
        ),
        migrations.AlterField(
            model_name='place',
            name='content',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='place',
            name='images',
            field=models.FileField(default='/default/images.jpg', upload_to='place/%Y/%m/%d'),
        ),
    ]
