# Generated by Django 2.1.5 on 2019-01-17 07:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190117_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='date_create',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='place',
            name='images',
            field=models.FileField(default='/default/default.png', upload_to='place/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='placedetails',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Place'),
        ),
    ]
