# Generated by Django 2.1.5 on 2019-01-21 08:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20190117_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedetails',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Null'),
        ),
        migrations.AlterField(
            model_name='placedetails',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='places.Place'),
        ),
        migrations.AlterField(
            model_name='placedetails',
            name='title',
            field=models.CharField(default='Null', max_length=250),
        ),
    ]
