# Generated by Django 2.1.5 on 2019-03-13 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('images', models.FileField(default='/default/default.png', upload_to='tour/%Y/%m/%d/%H/%M/%S/')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(default='Null')),
                ('date', models.FloatField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
