# Generated by Django 2.1.5 on 2019-04-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Image Editor', max_length=250)),
                ('images', models.FileField(default='/default/default.png', upload_to='editor/%Y/%m/%d/%H/%M/%S/')),
            ],
        ),
    ]
