# Generated by Django 2.1.5 on 2019-01-21 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Đà Nẵng', max_length=250)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(default='Núi', max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('images', models.FileField(default='/default/default.png', upload_to='house/%Y/%m/%d')),
                ('review', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('content', models.TextField(default='Null')),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
